### ISSUE TITLE
Enhancement: Allow detail view to be exported as spreadsheet

### ISSUE THREAD

**Issue by CorrineS** [Swarthmore/filescan#65] opened 2021-01-26 17:47 UTC
We could use this to mark which items should be exported for remediation, which are okay, and which have accessible online alternatives

For some reason I'm not able to add a label to this - should be an **enhancement**

**Comment by CorrineS** [comment] 2021-02-11 14:26
Didn't realize there was another issue requesting a similar thing - #21 These should be combined

**Comment by aruethe2** [comment] 2021-02-11 14:48
Duplicate of #21

**Closed by aruethe2** 2021-02-11 14:48 UTC
Labels: enhancement
