### ISSUE TITLE
Check into how to install Guzzle

### ISSUE THREAD

**Issue by aruethe2** [Swarthmore/filescan#3] opened 2017-06-23 13:42 UTC
Not sure how best to require Guzzle for all systems.  Currently just include files in the vendor directory.

**Comment by aruethe2** [comment] 2017-06-23 15:32
@mackensen suggests moving to a separate folder in the plugin with a note stating the version of Guzzle used.

**Comment by devnoot** [comment] 2019-07-24 19:19
It's not a bug but this should be fixed before pushing an official release

**Comment by aruethe2** [comment] 2019-07-24 19:40
Can we replace Guzzle with a Moodlelib function? 

I found a download_file_content function in [/lib/filelib.php](https://github.com/moodle/moodle/blob/master/lib/filelib.php)

> Fetches content of file from Internet (using proxy if defined). Uses cURL extension if present.

Further down in filelib.php, there are is a curl class with examples of downloading multiple files in parallel.  Search for "Download multiple files in parallel"

**Comment by devnoot** [comment] 2019-10-08 18:48
please see #49

**Comment by devnoot** [comment] 2019-10-15 13:23
fixed in pr #57

**Closed** 2019-10-15 13:22 UTC
Labels: bug
